apiVersion: v1
kind: Service
metadata:
  name: vax-cluster
  namespace: vax-cluster
  labels:
    app: vax-cluster
spec:
  clusterIP: None
  selector:
    app: vax-cluster
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: vax-cluster
  name: config
data:
  autostart: |
    vax0: autoboot
    vax1: autoboot
    vax2: autoboot
    vax3: autoboot
    vax4: autoboot
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vax-cluster
  namespace: vax-cluster
spec:
  serviceName: "vax-cluster"
  replicas: 5
  selector:
    matchLabels:
      app: vax-cluster
  template:
    metadata:
      labels:
        app: vax-cluster
    spec:
      hostNetwork: true
      containers:
      - name: simh-vax
        image: docker.flame.org/library/simh-vax:latest
        volumeMounts:
        - name: disks
          mountPath: /disks
        - name: config
          mountPath: /config
        securityContext:
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN
              - NET_RAW
      volumes:
        - name: config
          configMap:
            name: config

  volumeClaimTemplates:
  - metadata:
      name: disks
    spec:
      storageClassName: "longhorn"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
